Be-Secure/besecure-ce-env-repo

- besman-javaSpringdev-env.sh
- besman-javaSpringsec-env.sh
- besman-pythonDjangodev-env.sh
- besman-pythonDjangosec-env.sh
- javaSpringdev-env.config
- javaSpringsec-env.config
- list.txt
- pythonDjangodev-env.config
- pythonDjangosec-env.config
Following Environment Scripts are added to Env Repo
1) besman-javaSpringdev-env.sh
2) besman-javaSpringsec-env.sh
> Environment Script for Besman Spring Stack Topcoder Challenge

- README.md
- list.txt
- zaproxy/0.0.1/besman-zaproxy-BT-env-config.yaml
- zaproxy/0.0.1/besman-zaproxy-BT-env.sh
- zaproxy/0.0.1/besman-zaproxy-RT-env-config.yaml
- zaproxy/0.0.1/besman-zaproxy-RT-env.sh
https://github.com/Be-Secure/Be-Secure/issues/425
Added zaproxy RT BT env 0.0.1
updated list.txt
> zaproxy  RT BT env

- README.md
- lettuce/0.0.1/besman-lettuce-BT-env-config.yaml
- lettuce/0.0.1/besman-lettuce-BT-env.sh
- list.txt
lettuce: https://github.com/Be-Secure/Be-Secure/issues/480
> lettuce BT env

- README.md
updated readme file with latest available env
> updated readme file with latest available env

- ML/0.0.1/besman-ML-RT-env-config.yaml
Updated config file to work with watchtower playbook.
> Ml rt env update

- HWC-API/0.0.1/besman-HWC-API-BT-env-config.yaml
- ML/0.0.1/besman-ML-RT-env-config.yaml
- ML/0.0.1/besman-ML-RT-env.sh
- druid/0.0.1/besman-druid-BT-env-config.yaml
- fastjson/0.0.2/besman-fastjson-RT-env-config.yaml
- jackson-core/0.0.1/besman-jackson-core-BT-env-config.yaml
- jackson-databind/0.0.1/besman-jackson-databind-BT-env-config.yaml
- jackson-databind/0.0.1/besman-jackson-databind-RT-env-config.yaml
- lettuce/0.0.1/besman-lettuce-BT-env-config.yaml
- opencti/0.0.1/besman-opencti-RT-env-config.yaml
- zaproxy/0.0.1/besman-zaproxy-BT-env-config.yaml
- zaproxy/0.0.1/besman-zaproxy-RT-env-config.yaml
Updated config file for all ENVs.
> updated config files

- classic-model/0.0.1/besman-classic-model-RT-env.sh
> added cosign installation for classic model

- PyRIT/0.0.1/besman-PyRIT-RT-env-config.yaml
- PyRIT/0.0.1/besman-PyRIT-RT-env.sh
- environment-metadata.json
- list.txt
https://github.com/Be-Secure/besecure-ce-env-repo/issues/68
> Added PyRIT RT env script

- environment-metadata.json
- fleetbase/0.0.1/besman-fleetbase-RT-env-config.yaml
- fleetbase/0.0.1/besman-fleetbase-RT-env.sh
- list.txt
- odxtools/0.0.1/besman-odxtools-RT-env-config.yaml
- odxtools/0.0.1/besman-odxtools-RT-env.sh
fleetbase: https://github.com/Be-Secure/Be-Secure/issues/532
odxtools: https://github.com/Be-Secure/Be-Secure/issues/534
Performed the changes requested in the PR: https://github.com/Be-Secure/besecure-ce-env-repo/pull/75
> Added envs for fleetbase, odxtools

- environment-metadata.json
- list.txt
- logstash/0.0.1/besman-logstash-RT-env-config.yaml
- logstash/0.0.1/besman-logstash-RT-env.sh
- privacyidea/0.0.1/besman-privacyidea-RT-env-config.yaml
- privacyidea/0.0.1/besman-privacyidea-RT-env.sh
- prometheus/0.0.1/besman-prometheus-RT-env-config.yaml
- prometheus/0.0.1/besman-prometheus-RT-env.sh
logstash: https://github.com/Be-Secure/Be-Secure/issues/235
prometheus: https://github.com/Be-Secure/Be-Secure/issues/299
privacyidea: https://github.com/Be-Secure/Be-Secure/issues/377
> Adding logstash, prometheus, privacyidea RT env

- environment-metadata.json
- guardrails/0.0.1/besman-guardrails-RT-env-config.yaml
- guardrails/0.0.1/besman-guardrails-RT-env.sh
- list.txt
Added env script for guardrails
> Added env script for guardrails

- environment-metadata.json
- list.txt
- threat-dragon/0.0.1/besman-threat-dragon-RT-env-config.yaml
- threat-dragon/0.0.1/besman-threat-dragon-RT-env.sh
threat-dragon: https://github.com/Be-Secure/Be-Secure/issues/185
> threat-dragon RT env

- environment-metadata.json
- grype/0.0.1/besman-grype-RT-env-config.yaml
- grype/0.0.1/besman-grype-RT-env.sh
- list.txt
grype: https://github.com/Be-Secure/Be-Secure/issues/126
> grype RT env

- environment-metadata.json
- list.txt
- trivy/0.0.1/besman-trivy-RT-env-config.yaml
- trivy/0.0.1/besman-trivy-RT-env.sh
trivy: https://github.com/Be-Secure/Be-Secure/issues/179
> trivy RT env

- bandit/0.0.1/besman-bandit-RT-env-config.yaml
- bandit/0.0.1/besman-bandit-RT-env.sh
- environment-metadata.json
- list.txt
bandit: https://github.com/Be-Secure/Be-Secure/issues/361
> bandit RT env

- environment-metadata.json
- kyverno/0.0.1/besman-kyverno-RT-env-config.yaml
- kyverno/0.0.1/besman-kyverno-RT-env.sh
- list.txt
kyverno: https://github.com/Be-Secure/Be-Secure/issues/221
> kyverno RT env

- TheHive/0.0.1/besman-TheHive-RT-env-config.yaml
- TheHive/0.0.1/besman-TheHive-RT-env.sh
- environment-metadata.json
- list.txt
TheHive: https://github.com/Be-Secure/Be-Secure/issues/214
> TheHive RT env

- environment-metadata.json
- list.txt
- openpilot/0.0.1/besman-openpilot-RT-env-config.yaml
- openpilot/0.0.1/besman-openpilot-RT-env.sh
openpilot: https://github.com/Be-Secure/Be-Secure/issues/536
> openpilot RT env

- environment-metadata.json
- list.txt
- open-adas/0.0.1/besman-open-adas-RT-env-config.yaml
- open-adas/0.0.1/besman-open-adas-RT-env.sh
open-adas: https://github.com/Be-Secure/Be-Secure/issues/535
> open-adas RT env

- environment-metadata.json
- list.txt
- nightvision/0.0.1/besman-nightvision-RT-env-config.yaml
- nightvision/0.0.1/besman-nightvision-RT-env.sh
nightvision: https://github.com/Be-Secure/Be-Secure/issues/545
> nightvision RT env

- environment-metadata.json
- list.txt
- oscc/0.0.1/besman-oscc-RT-env-config.yaml
- oscc/0.0.1/besman-oscc-RT-env.sh
oscc: https://github.com/Be-Secure/Be-Secure/issues/544
> oscc RT env

- environment-metadata.json
- list.txt
- openauto/0.0.1/besman-openauto-RT-env-config.yaml
- openauto/0.0.1/besman-openauto-RT-env.sh
openauto: https://github.com/Be-Secure/Be-Secure/issues/543
> openauto RT env

- apollo/0.0.1/besman-apollo-RT-env-config.yaml
- apollo/0.0.1/besman-apollo-RT-env.sh
- environment-metadata.json
- list.txt
apollo: https://github.com/Be-Secure/Be-Secure/issues/542
> apollo RT env

- environment-metadata.json
- gitleaks/0.0.1/besman-gitleaks-RT-env-config.yaml
- gitleaks/0.0.1/besman-gitleaks-RT-env.sh
- list.txt
gitleaks: https://github.com/Be-Secure/Be-Secure/issues/340
> gitleaks RT env

- README.md
Contribution Guidelines added in Readme
> Contribution Guidelines

- aifairness360/0.0.1/besman-aifairness360-RT-env-config.yaml
- aifairness360/0.0.1/besman-aifairness360-RT-env.sh
- beckn-onix/0.0.1/besman-beckn-onix-RT-env-config.yaml
- beckn-onix/0.0.1/besman-beckn-onix-RT-env.sh
- beslab/0.0.1/besman-beslab-RT-env-config.yaml
- beslab/0.0.1/besman-beslab-RT-env.sh
- besman/0.0.1/besman-besman-RT-env-config.yaml
- besman/0.0.1/besman-besman-RT-env.sh
- bliman/0.0.1/besman-bliman-RT-env-config.yaml
- bliman/0.0.1/besman-bliman-RT-env.sh
- buyer-ui/0.0.1/besman-buyer-ui-RT-env-config.yaml
- buyer-ui/0.0.1/besman-buyer-ui-RT-env.sh
- environment-metadata.json
- giskard/0.0.1/besman-giskard-RT-env-config.yaml
- giskard/0.0.1/besman-giskard-RT-env.sh
- grimoirelab/0.0.1/besman-grimoirelab-RT-env-config.yaml
- grimoirelab/0.0.1/besman-grimoirelab-RT-env.sh
- instructlab/0.0.1/besman-instructlab-RT-env-config.yaml
- instructlab/0.0.1/besman-instructlab-RT-env.sh
- list.txt
- ms-sbom-tool/0.0.1/besman-ms-sbom-tool-RT-env-config.yaml
- ms-sbom-tool/0.0.1/besman-ms-sbom-tool-RT-env.sh
- oss-fuzz-gen/0.0.1/besman-oss-fuzz-gen-RT-env-config.yaml
- oss-fuzz-gen/0.0.1/besman-oss-fuzz-gen-RT-env.sh
- oss-fuzz/0.0.1/besman-oss-fuzz-RT-env-config.yaml
- oss-fuzz/0.0.1/besman-oss-fuzz-RT-env.sh
- seller-ui/0.0.1/besman-seller-ui-RT-env-config.yaml
- seller-ui/0.0.1/besman-seller-ui-RT-env.sh
Basic env with lifecycle function for 13 pending from O31E_security_tool list
BLiman, BeSMan, BeSLab, MS-SBOM, OSS-Fuzz, OSS-Fuzz-Zen, GrimoireLab, Giskard, InstructLab, beckn-onix, seller-ui, buyer-ui, AI-Fairness-360
> pending basic env for POI

- AIF360/0.0.1/besman-AIF360-RT-env-config.yaml
- AIF360/0.0.1/besman-AIF360-RT-env.sh
- ScoreCard/0.0.1/besman-scorecard-RT-env-config.yaml
- ScoreCard/0.0.1/besman-scorecard-RT-env.sh
- beslab/0.0.1/besman-beslab-RT-env-config.yaml
- beslab/0.0.1/besman-beslab-RT-env.sh
- besman/0.0.1/besman-besman-RT-env-config.yaml
- besman/0.0.1/besman-besman-RT-env.sh
- bliman/0.0.1/besman-bliman-RT-env-config.yaml
- bliman/0.0.1/besman-bliman-RT-env.sh
- environment-metadata.json
- sbom-tool/0.0.1/besman-sbom-tool-RT-env-config.yaml
- sbom-tool/0.0.1/besman-sbom-tool-RT-env.sh
updated be-secure projects envs
> Updated beslab, bliman and besman env

- AIX360/0.0.1/besman-AIX360-RT-env-config.yaml
- AIX360/0.0.1/besman-AIX360-RT-env.sh
- OSSVerse-Buyer-App/0.0.1/besman-OSSVerse-Buyer-App-RT-env-config.yaml
- OSSVerse-Buyer-App/0.0.1/besman-OSSVerse-Buyer-App-RT-env.sh
- adversarial-robustness-toolbox/0.0.1/besman-adversarial-robustness-toolbox-RT-env.sh
- buyer-ui/0.0.1/besman-buyer-ui-RT-env-config.yaml
- buyer-ui/0.0.1/besman-buyer-ui-RT-env.sh
- criticality_score/0.0.1/besman-criticality_score-RT-env-config.yaml
- criticality_score/0.0.1/besman-criticality_score-RT-env.sh
- fossology/0.0.1/besman-fossology-RT-env-config.yaml
- fossology/0.0.1/besman-fossology-RT-env.sh
- giskard/0.0.1/besman-giskard-RT-env-config.yaml
- giskard/0.0.1/besman-giskard-RT-env.sh
- grimoirelab/0.0.1/besman-grimoirelab-RT-env-config.yaml
- grimoirelab/0.0.1/besman-grimoirelab-RT-env.sh
- instructlab/0.0.1/besman-instructlab-RT-env-config.yaml
- instructlab/0.0.1/besman-instructlab-RT-env.sh
- lime/0.0.1/besman-lime-RT-env-config.yaml
- lime/0.0.1/besman-lime-RT-env.sh
- oasp-seller-app/0.0.1/besman-oasp-seller-app-RT-env-config.yaml
- oasp-seller-app/0.0.1/besman-oasp-seller-app-RT-env.sh
- opencti/0.0.1/besman-opencti-RT-env-config.yaml
- opencti/0.0.1/besman-opencti-RT-env.sh
- oss-fuzz-gen/0.0.1/besman-oss-fuzz-gen-RT-env-config.yaml
- oss-fuzz-gen/0.0.1/besman-oss-fuzz-gen-RT-env.sh
- seller-ui/0.0.1/besman-seller-ui-RT-env-config.yaml
- seller-ui/0.0.1/besman-seller-ui-RT-env.sh
- spdx-sbom-generator/0.0.1/besman-spdx-sbom-generator-RT-env-config.yaml
- spdx-sbom-generator/0.0.1/besman-spdx-sbom-generator-RT-env.sh
updated env - added cycloneDX setup
> updated env - added cycloneDX setup

- Environments.md
> Merge Github action changes back

- .github/workflows/Update_Envs_Published_Develop.yml
Added fixes to github action for repo name change
> changed the github action for new repo changes

- .github/workflows/Update_Envs_Published_Develop.yml
> updated actions

- cogito/0.0.1/besman-cogito-assessment-env-config.yaml
- cogito/0.0.1/besman-cogito-assessment-env.sh
- environment-metadata.json
- gemma3/0.0.1/besman-gemma3-assessment-env-config.yaml
- list.txt
New assessment env for LLM cogito to perform LLM Security Benchmark
> New assessment env for cogito llm

- LLMSafety/0.0.1/besman-LLMSafety-assessment-env-config.yaml
- LLMSafety/0.0.1/besman-LLMSafety-assessment-env.sh
- environment-metadata.json
> Fixed bugs related to installation of LLM Safety env

- BeSLighthouse/0.0.1/besman-BeSLighthouse-RT-env.sh
- BeSLighthouse/0.0.1/besman-BeSLihthouse-RT-env-config.yaml
> Added BeSLigthouse

- environment-metadata.json
Added BeSLighthouse into metadata
> Added BeSLighthouse in Metadata

- BeSLighthouse/0.0.1/besman-BeSLighthouse-RT-env.sh
> updated BeSLighthouse env

- BeSLighthouse/0.0.1/besman-BeSLighthouse-RT-env-config.yaml
- environment-metadata.json
- gitlabhq/0.0.1/besman-gitlabhq-RT-env-config.yaml
- gitlabhq/0.0.1/besman-gitlabhq-RT-env.sh
- list.txt
- ollama/0.0.1/besman-ollama-RT-env-config.yaml
- ollama/0.0.1/besman-ollama-RT-env.sh
created gitlabhq RT env for securoty assessment like sonarqube, scorecard, SBOM, criticality_score, cbom etc
> gitlabhq RT env for assessment
